import streamlit as st

from pdf_utils import generate_pdf

from logging_utils import (
    log_event,
)

# from gemini_utils import apply_suggested_improvements


def render_phase2():

    if not st.session_state.get("lesson_plan", ""):
        return

    st.divider()

    st.header("Review, Refine and Finalize Lesson Plan")

    st.info(
        "Review the lesson plan generated by the AI."
    )

    # ----------------------------------------------------
    # Generated Lesson Plan
    # ----------------------------------------------------

    st.subheader("📘 Generated Lesson Plan")

    with st.container(border=True):

        st.markdown(
            """
            <div style="
                background-color:#f8fbff;
                padding:15px;
                border-left:6px solid #1F4E79;
                border-radius:8px;
                margin-bottom:10px;
            ">
            <h4 style="color:#1F4E79;margin-top:0;">
            AI Generated Lesson Plan
            </h4>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.text_area(
        "",
        value=st.session_state.lesson_plan,
        height=700,
        disabled=True,
        label_visibility="collapsed",
    )

    st.divider()

    # ----------------------------------------------------
    # AI Lesson Review
    # ----------------------------------------------------

    if st.session_state.get("lesson_review"):

        st.subheader("📋 Evaluation Summary")

        st.info(
            "The AI has reviewed the generated lesson plan and provided the Evaluation summary. "
            "The suggestions are optional and can be considered based on your teaching preferences."
        )

        st.text_area(
            "Validation Summary",
            value=st.session_state.lesson_review,
            height=300,
            disabled=True,
        )

    st.divider()

    # ----------------------------------------------------
    # Teacher Editing
    # ----------------------------------------------------
    
    if "edit_mode" not in st.session_state:
        st.session_state.edit_mode = False

    if st.button("✏️ Edit Lesson Plan"):

        st.session_state.edit_mode = True

        log_event(
            "EDIT_START"
        )

    if st.session_state.edit_mode:

        edited_plan = st.text_area(
            "Modify Lesson Plan",
            value=st.session_state.lesson_plan,
            height=700,
        )

        col1, col2 = st.columns(2)

        with col1:

            if st.button("Save Changes"):

                st.session_state.lesson_plan = edited_plan

                st.session_state.edit_mode = False

                log_event(
                    "EDIT_SAVE"
                )

                st.success(
                    "Lesson plan updated successfully!"
                )

                st.rerun()

        with col2:

            if st.button("Cancel Editing"):

                st.session_state.edit_mode = False

                log_event(
                    "EDIT_CANCEL"
                )

                st.rerun()

    st.divider()

    # ----------------------------------------------------
    # Download Final Lesson Plan
    # ----------------------------------------------------

    pdf_file = generate_pdf(
        st.session_state.lesson_plan
    )

    st.download_button(
        label="📄 Download Final Lesson Plan as PDF",
        data=pdf_file,
        file_name="lesson_plan.pdf",
        mime="application/pdf",
        on_click=lambda: log_event(
            "PDF_DOWNLOAD"
        ),
    )

    st.divider()

    if st.button("Finish"):

        log_event(
            "SESSION_FINISH"
        )

        st.success(
            "Lesson planning completed successfully!"
        )